### ISSUE TITLE
[XRT] No device found during compiling LZ4 L2

### ISSUE THREAD

**Issue by wonsikleee** [Xilinx/Vitis_Libraries#10]
Hi,

I'm trying to generate the bitstream file with files in lz4 l2.
Compiling sw_emu/hw_emu are both fine.
But after I set the target as hw, it gives "[XRT] No device found" error message.
The board that I'm using is U250 and it can be found either lspci and xbmgmt scan.
Is there any possible way to fix it?

Thanks,

**Comment by mahinlma** [comment]
try `xbutil validate` ,
If this fails, then cold reboot your machine and try the same command again

**Comment by vt-lib-support** [comment]
@wonsikleee  closing this issue as it is specific to system setup and board installation etc.
