### ISSUE TITLE
Y2K22 error with revision number in builds

### ISSUE THREAD

**Issue by arjunr2** [Xilinx/Vitis_Libraries#104]
Vitis builds have failed since Jan 1, 2022, possibly due to the format of the stored year for the revision number in the builds. Could someone look into this?

**Comment by vt-lib-support** [comment]
Thanks for reporting this.  It has already been reported and is being investigated.  For additional discussion please refer to the following Xilinx Forums Post:

https://support.xilinx.com/s/question/0D52E00006uxYjmSAE/bug-report-vivado-20212-revision-number-overflow-after-new-year?language=en_US

**Comment by keryell** [comment]
Do not close issues about problems which still do exist, otherwise people might open them again and again since they will hit the problems.

**Comment by vt-lib-support** [comment]
This issue has been resolved:

https://support.xilinx.com/s/article/76960?language=en_US
