### ISSUE TITLE
xilLz4CompressStream outputs no more than 4.1KBytes

### ISSUE THREAD

**Issue by luojw-dwr** [Xilinx/Vitis_Libraries#11]
I'm trying to utilize xilLz4CompressStream as part of my kernel. When the input size is large to some extent (I have not  found the certain threshold), the output size will be 4.1KBytes. This behaviour is conformed by putting both a 98KBytes text and its first 49KBytes half but achieving the same two 4.1KBytes outputs (the sameness is conformed with diff). In addition, xilLz4CompressStream consumes the 'extra' inputs correctly (though not generating the corresponding outputs), i.e. the previous stages in the dataflow does not stall due to this behaviour.

This behaviour is found in software emulation, hardware emulation and true hardware. When this behaviour is observed, though the results of hardware emulation and true hardware are the same (confirmed by diff), the results of software emulation and hardware emulation (also the hardware) differ.

p.s. To let the core outputs only after receiving some input, I removed the HLS RESOURCE pragmas.

**Comment by vt-lib-support** [comment]
@luojw-dwr we have updated the source code recently can you please try and let us know if you still face the same issue.

**Comment by vt-lib-support** [comment]
Closing this issue as there is no further update on this. Reopen if this issue still persists.
