### ISSUE TITLE
Possible Data Corruption in Example Design_Tutorials/06-fft2d_AIEvsHLS

### ISSUE THREAD

**Issue by K-Wu** [Xilinx/Vitis_Libraries#115]
When running `aiesimulator` on `Design_Tutorials/06-fft2d_AIEvsHLS`, I continue to get the following messages.

> WARNING : Line skipped, invalid number of data samples on line, got 1 expected 8

To work this around, I replaced `1.0` with `1` in the two input files `Design_Tutorials/06-fft2d_AIEvsHLS/AIE/design/aie_src/aiesim_data/input0.txt` and `Design_Tutorials/06-fft2d_AIEvsHLS/AIE/design/aie_src/aiesim_data/input1.txt`. This suppressed the aforementioned warning messages.

I still want to check if the dataset files content is correct and understand the best way to fix this. Thanks!

**Comment by vt-lib-support** [comment]
@K-Wu thank you for reporting this issue.  The problem is with one of the Vitis Design Tutorials.  This should be reported in the Vitis Tutorials Github Issues page.
 - (https://github.com/Xilinx/Vitis-Tutorials/issues)
