### ISSUE TITLE
Issue with cosim of L1 FFT example

### ISSUE THREAD

**Issue by bigglasses93** [Xilinx/Vitis_Libraries#117]
Hello, I'm trying to builde the L1 FFT example from https://github.com/Xilinx/Vitis_Libraries/tree/master/dsp/L1/examples/1Dfloat_impluse

When I run as it is, the cosim can finish and I can get latency of 1 run.
But as the file src/main.cpp suggests (line 37-38), to measure II, I increase the loop count from 1 (original) to make several runs. 

    for (int t = 0; t < 4; ++t) {
        // Added Dummy loop iterations
        // to make II measurable in cosim
        fft_top(inData, outData);
    }

However, my co-simulation cannot finish after changing this number of tests. 
So how can I measure the II of this module?

**Comment by vt-lib-support** [comment]
Hi, the `fft_top` function is taking a stream as input, so after one run, it has emptied the input stream. With your change, the module would hang because its input is empty after first call. If you want the design to run 4 times, you should preload the `inData` with data first.
