### ISSUE TITLE
condition where Vitis HLS tools consistently creates undersized hls stream buffers which lead to deadlock

### ISSUE THREAD

**Issue by ethansieg** [Xilinx/Vitis_Libraries#118]
Vitis HLS synthesis tool consistently infers design that will deadlock due to undersized buffers (the hls data streams buffers produced by the xf::cv::Mat object) in vitis vision library when you have an algorithm which requires splitting data (according to UG1399 p332) to adhere to the single producer single consumer model required by HLS DATAFLOW.

**Comment by vt-lib-support** [comment]
Hi @ethansieg ,

Feature of providing custom depth to hls::stream formed by the xf::cv::Mat is in works.

**Comment by vt-lib-support** [comment]
Hi @ethansieg ,

The above said feature has been added in the latest release.
