### ISSUE TITLE
Vitis Vision library does not allow you to manually specify buffer size of individual xf::cv::Mat objects

### ISSUE THREAD

**Issue by ethansieg** [Xilinx/Vitis_Libraries#119]
If you specify the XFCVDEPTH parameter when you define a xf::cv::Mat container so that you can manually control the hls stream buffer depth, it breaks most if not all vitis vision functions because there template function definitions do not handle the XFCVDEPTH parameter.

as a work around, it should be possible to wrap the xf::cv::Mat object in a hls stream but the pragma to define the hls stream depth seems to have stopped working in 2021.2.

**Comment by vt-lib-support** [comment]
Hi @ethansieg ,

Thanks for reporting this.

Hi @ethansieg ,

The feature of providing custom depth to hls::stream formed by the xf::cv::Mat is in works.

**Comment by vt-lib-support** [comment]
Hi @ethansieg ,

This feature has been added in the latest release.
