### ISSUE TITLE
Contradictory information in DSP documentation

### ISSUE THREAD

**Issue by gareth-xlnx** [Xilinx/Vitis_Libraries#12]
In https://xilinx.github.io/Vitis_Libraries/dsp/user_guide/L1.html section "Start with floating point model" (direct link https://xilinx.github.io/Vitis_Libraries/dsp/user_guide/L1.html#start-with-floating-point-model) there are two lines for the `complex_wrapper<float>` type, one saying Synthesis is supported and one saying not. I assume one of these should be `complex_wrapper<double>` ?

**Comment by vt-lib-support** [comment]
issue fixed
