### ISSUE TITLE
Vitis_Libraries/vision/L3/ Makefile does wrong checks for embedded devices

### ISSUE THREAD

**Issue by lino-alves** [Xilinx/Vitis_Libraries#121]
Hi @vt-lib-support,

When attempting to make the example
[https://github.com/Xilinx/Vitis_Libraries/tree/master/vision/L3/examples/isppipeline](https://github.com/Xilinx/Vitis_Libraries/tree/master/vision/L3/examples/isppipeline)
for an embedded device, the Makefile fails due to missing PCIe environment variables (OPENCV_INCLUDE and OPENCV_LIB).
`Cannot find OpenCV include path. Please set OPENCV_INCLUDE variable
make: *** [Makefile:227: check_env] Error 1`
`Cannot find Opencv lib path. Please set OPENCV_LIB variable
make: *** [Makefile:230: check_env] Error 1`

The Makefile is doing the wrong checks for the embedded devices.
This was fixed in #42 but apparently the fix was only implemented in L2 and not in L3.

Exporting the PCIe missing variables to the correct path or setting them to zero solves this issue.

**Comment by vt-lib-support** [comment]
Hi @lino-alves ,

Thanks for reporting this. This has been fixed in the latest 2022.1 release.
