### ISSUE TITLE
FAST Corner Detection with DATAFLOW

### ISSUE THREAD

**Issue by norabarlow** [Xilinx/Vitis_Libraries#127]
Co-simulation does not finish for the FAST corner detection kernel if I don't use the DATAFLOW pragma.

Does/should `xf::cv::fast` work without the DATAFLOW pragma?

**Comment by vt-lib-support** [comment]
Hi @norabarlow ,

Modifying the kernel may cause the function (in this case removing the DATAFLOW) to behave abnormally.
