### ISSUE TITLE
Issue in running Vitis Vision Library on board

### ISSUE THREAD

**Issue by Sarika124** [Xilinx/Vitis_Libraries#140]
Hi,
I am working on Vitis Vision libraries targeting Alveo U250 board with following system info, 
      OS: Ubuntu 18.04.6
      Kernel version : 4.15.0-76 (generic)
      XRT version: 2021.2  
      Vitis version: 2021.2
     Device: xilinx_u250_gen3x16_xdma_3_1_202020_1

I am trying to run vision/L2/examples. Till command "_**make host xclbin TARGET=hw >**_ " run successfully. But issue in running " **_make run TARGET=hw_**".
![Screenshot from 2022-06-27 10-39-05](https://user-images.githubusercontent.com/104189887/175863857-db1887ed-a09b-4927-88fe-33db29fa2f5d.png)

Is this issue due to U250 card? Can anyone please help!

Thanks in Advance!!

**Comment by vt-lib-support** [comment]
Hi @Sarika124 ,

Vitis Vision library has been tested to work on the devices mentioned in the [README](https://github.com/Xilinx/Vitis_Libraries/tree/master/vision#hardware-and-software-requirements). 
We suggest you to use one of them.

**Comment by Sarika124** [comment]
Thank U for the quick response.
