### ISSUE TITLE
Dynamic Filter design principle in database library

### ISSUE THREAD

**Issue by Shiyunfeng96** [Xilinx/Vitis_Libraries#158]
Hello, I have recently been doing some development on Xilinx FPGA based on the Database library in your Vitis Library. I found that in the Dynamic Filter of the L1 part, I finally need to use the 10bits address to read a True Table. I am very I wonder why this True Table is designed. Is it possible to perform the And operation on the 10bits address?

**Comment by vt-lib-support** [comment]
Hi, the idea is to support arbitrary logic operation on top of comparison results.
For example, `select a from table where a < 10 or a> 20;`. 
Such filter condition cannot be expressed with a simple AND tree.
