### ISSUE TITLE
Vitis Software Platform for Trial

### ISSUE THREAD

**Issue by bhavna-cst** [Xilinx/Vitis_Libraries#16]
Hi,

Is there a way to get trail version of the software?
I would like to simulate the library, to develop expertise in High Level Synthesis using Vitis.

Thanks & Regards,
Bhavna

**Comment by gareth-xlnx** [comment]
HI @bhavna-cst , the Vitis unified software platform is free for [Xilinx boards](https://www.xilinx.com/products/design-tools/vitis/vitis-platform.html#deployment). Get started here:

https://www.xilinx.com/products/design-tools/vitis.html

**Comment by vt-lib-support** [comment]
question answered
