### ISSUE TITLE
Missing semicolon on line 27 of xf_fintech_cf_black_scholes.cpp

### ISSUE THREAD

**Issue by xilinx-mikeh** [Xilinx/Vitis_Libraries#17]
line 27 is missing a semicolon:
https://github.com/Xilinx/Vitis_Libraries/blob/master/quantitative_finance/L3/tests/CFBlackScholes/xf_fintech_cf_black_scholes.cpp

**Comment by keryell** [comment]
Indeed...
Perhaps you can make a PR?
And while you are on it, could you replace the `static const` by a `constexpr`?

**Comment by vt-lib-support** [comment]
issue fixed
