### ISSUE TITLE
Document differences between hash_join_v3_sc and hash_join_v3_bp

### ISSUE THREAD

**Issue by nickbeckwith** [Xilinx/Vitis_Libraries#18]
Would be great if you could document a description on the differences between the *sc and *bp versions of the hash_join_v3 tests found in the Vitis_Libraries/database/L1/tests/hw folder: [https://github.com/Xilinx/Vitis_Libraries/tree/master/database/L1/tests/hw](url)

**Comment by vt-lib-support** [comment]
issue fixed
