### ISSUE TITLE
hls::erf and hls::erfc not linking in hw_emu

### ISSUE THREAD

**Issue by dylanbespalko** [Xilinx/Vitis_Libraries#20]
When I replace calls to `hls::erf` and `hls::ercf` with `hls::exp` everything works fine.

I have attached the logs.
[v++.log](https://github.com/Xilinx/Vitis_Libraries/files/4664339/v%2B%2B.log)
[link.steps.log](https://github.com/Xilinx/Vitis_Libraries/files/4664340/link.steps.log)

**Comment by vt-lib-support** [comment]
hi dylanbespalko,

This issue is not vitis library related, so I will close it. Please post your question to the Xilinx developer forum to get the supports:
        https://forums.xilinx.com/t5/High-Level-Synthesis-HLS/bd-p/hls

Thanks!
