### ISSUE TITLE
bug in xf::cv::AXIvideo2xfMat 

### ISSUE THREAD

**Issue by Ali-Flt** [Xilinx/Vitis_Libraries#26]
Hi, 
I'm trying to use xf::cv::AXIvideo2xfMat and there seem to be a bug inside the code causing the synthesizer to error.
the error is as followed:
```
ERROR: [HLS 200-977] Argument 'stream_in_1_V' failed dataflow checking: it can only be used in one process.
WARNING: [HLS 200-992] Argument 'stream_in_1_V' has read operations in process function 'Loop_loop_wait_for_start_proc26'.
Resolution: For help on HLS 200-992 see www.xilinx.com/html_docs/xilinx2020_1/hls-guidance/200-992.html
WARNING: [HLS 200-992] Argument 'stream_in_1_V' has read operations in process function 'Loop_loop_height_proc'.
Resolution: For help on HLS 200-992 see www.xilinx.com/html_docs/xilinx2020_1/hls-guidance/200-992.html
```
I think it is because the stream input is being read in two different loops in the function code in xf_infra.hpp file. (loop_wait_for_start and loop_height)

a link to this problem in Xilinx forums: 
[https://forums.xilinx.com/t5/High-Level-Synthesis-HLS/HLS-failed-dataflow-checking/td-p/1049741](https://forums.xilinx.com/t5/High-Level-Synthesis-HLS/Vitis-Vision-library-xf-cv-cvMat2AXIvideoxf-problem/m-p/1142291#M21590)
can you please fix this issue cause I really need this function for my work.

thanks
Ali

**Comment by canonant** [comment]
I meet the same problem, could this bug be fixed as soon as possible?

**Comment by Ali-Flt** [comment]
After waiting for the Xilinx Employees for a fix and not receiving even a comment, I've tried to fix the function myself. I tested it in Csim and in hardware implementation and it seems to be working. What I basically did was merging the loop_wait_for_start and loop_height  in a single loop. I've attached the modified "xf_infra.hpp" file. 

[xf_infra.zip](https://github.com/Xilinx/Vitis_Libraries/files/5151865/xf_infra.zip)

**Comment by canonant** [comment]
@Ali-Flt thanks for you answer, after test you code, I can build this function with "dataflow". but I met some question after load as hardware,[https://forums.xilinx.com/t5/Vitis-Acceleration-SDAccel-SDSoC/K2K-AXIvideo2xfMat-not-worked/td-p/1145308](url), did you met this problem.

**Comment by Ali-Flt** [comment]
Hi @canonant ,
Unfortunately I have never worked with SDAccel and have no Idea what your problem might be, But I will share the code of my Core and C Test bench, in which I used this function, and maybe it will give you an idea about what the issue might be.
I doubt that your problem is from the AXIvideo2xfMat because I tested my modified function in design and in worked properly in Linux Userspace.
[simple_erosion.zip](https://github.com/Xilinx/Vitis_Libraries/files/5156824/simple_erosion.zip)

**Comment by vt-lib-support** [comment]
Hi @Ali-Flt / @canonant 
We have reproduced the issue and we are validating the fix we

**Comment by vt-lib-support** [comment]
Issue fixed.
