### ISSUE TITLE
bug in  xf::cv::cvMat2AXIvideoxf function

### ISSUE THREAD

**Issue by Ali-Flt** [Xilinx/Vitis_Libraries#27]
Hi, 
I'm trying to use the xf::cv::cvMat2AXIvideoxf function in my test bench for debugging purpose and it seems like the whole 
xf_axi.hpp file has problems and doesn't compile at all. Are there any files i need to include before this file or is this actually a bug not letting the code to even compile?

here is a link to my exact issue in xilinx forums:
[https://forums.xilinx.com/t5/High-Level-Synthesis-HLS/Vitis-Vision-library-xf-cv-cvMat2AXIvideoxf-problem/m-p/1142291#M21590](https://forums.xilinx.com/t5/High-Level-Synthesis-HLS/Vitis-Vision-library-xf-cv-cvMat2AXIvideoxf-problem/m-p/1142291#M21590)

**Comment by vt-lib-support** [comment]
Issue fixed.
