### ISSUE TITLE
where can I find the standalone hls example using Vitis_libraries vt::cv?

### ISSUE THREAD

**Issue by 3togo** [Xilinx/Vitis_Libraries#30]
xfopencv was superseded by vitis_libraries.  However, I cannot find any examples on how to use vitis libraries 
in standalone HLS application.  

Below is for using xfopencv
https://github.com/Xilinx/xfopencv/tree/master/HLS_Use_Model/Standalone_HLS_Example

How about for using vt::cv?

**Comment by vt-lib-support** [comment]
Hello @3togo,

There is no vt::cv, it is still xf::cv. They are the same xfOpenCV functions made compatible to Vitis tool and has been rebranded as Vitis Vision library. 

All the functions under [L1/examples](https://github.com/Xilinx/Vitis_Libraries/tree/master/vision/L1/examples) and [L1/tests](https://github.com/Xilinx/Vitis_Libraries/tree/master/vision/L1/tests) folders can be built as standalone HLS applications.

Please follow the [README](https://github.com/Xilinx/Vitis_Libraries/blob/master/vision/L1/README.md) on how to run them,  and for more information on Vitis Vision functions, [here ](https://xilinx.github.io/Vitis_Libraries/vision/2020.1/index.html) is the documentation.
