### ISSUE TITLE
Issues with sd_card generation for embedded Vitis_Libraries/vision/L2/ examples

### ISSUE THREAD

**Issue by mkycrb** [Xilinx/Vitis_Libraries#32]
From these instructions: https://github.com/Xilinx/Vitis_Libraries/tree/master/vision/L2#commands-to-run

For an edge device creation of sd_card is not as simple as:

make run TARGET=< sw_emu|hw_emu|hw > BOARD=Zynq ARCH=< aarch32 | aarch64 >

As of 2020.1 the following will creep up:

- Makefile 'run' target is now using SYSROOT for more than just the sysroot location. Consequently, it's not enough to just point to a sysroot location. The provided path has to meet specific requirements. In particular, it expects the sysroot to be located as a child directory of an extracted "Common images for Embedded Vitis platforms" archive (which isn't the default SDK location). For example, in the case of ZynqMP the sysroot must have the path .../xilinx-zynqmp-common-v2020.1/sysroots/aarch64-xilinx-linux
- Makefile 'run' target also expects an uncompressed version of the rootfs, but the archive of common components provides a compressed version. So, for example, the file .../xilinx-zynqmp-common-v2020.1/rootfs.ext4.gz must be extracted at it's current location for the 'run' target to succeed.

Probably best to update the Makefile such that these requirements aren't necessary.  For example, use separate env-vars for location of sysroot and location of common-archive contents such that there is no "../.." dependency.  And ideally the Makefile would work with the supplied rootfs.ext4.gz otherwise additional instructions are needed.

Instructions should also explicitly state the need for the archive from "Common images for Embedded Vitis platforms".

**Comment by vt-lib-support** [comment]
@mkycrb 
The Makefiles have been updated and the README commands modified suitably in the latest release.
Please reopen if issue persists. Thanks for raising the issue.
