### ISSUE TITLE
/usr/lib/libgdal.so.20: undefined reference to `xmlXPathRegisterNs@LIBXML2_2.4.30' /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlNanoHTTPCleanup@LIBXML2_2.4.30'

### ISSUE THREAD

**Issue by 3togo** [Xilinx/Vitis_Libraries#33]
I have trying to test compiling Vitis_Libraries/vision/L1/examples/sgbm with the following bash scripts and got numerous undefined errors.
eli@elli-A17-R4:~/gitee/Vitis_Libraries/vision/L1/examples/sgbm$ cat runme.sh

> #! /bin/bash
> source /tools/Xilinx/Vitis/2020.1/settings64.sh
> source /opt/xilinx/xrt/setup.sh
> export DEVICE=/opt/xilinx/platforms/xilinx_u200_xdma_201830_2/xilinx_u200_xdma_201830_2.xpfm
> export OPENCV_INCLUDE=/usr/include/opencv2
> export OPENCV_LIB=/usr/lib/x86_64-linux-gnu
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPENCV_LIB
> make  run CSIM=1 XPART='xcu200-fsgd2104-2-e' BOARD=Zynq ARCH=aarch64
> #make  run CSIM=1 BOARD=Zynq ARCH=aarch64

As the version of libxml2 in Ubuntu Bionic 18.04 should be 2.9.4+dfsg1-6.1ubuntu1.3, where is the version of LIBXML2_2.4.30 that the errors messages are referring to?

> eli@elli-A17-R4:~/gitee/Vitis_Libraries/vision/L1/examples/sgbm$ ./runme.sh
> XILINX_XRT      : /opt/xilinx/xrt
> PATH            : /opt/xilinx/xrt/bin:/tools/Xilinx/Vitis/2020.1/bin:/tools/Xilinx/Vitis/2020.1/gnu/microblaze/lin/bin:/tools/Xilinx/Vitis/2020.1/gnu/arm/lin/bin:/tools/Xilinx/Vitis/2020.1/gnu/microblaze/linux_toolchain/lin64_le/bin:/tools/Xilinx/Vitis/2020.1/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/tools/Xilinx/Vitis/2020.1/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/tools/Xilinx/Vitis/2020.1/gnu/aarch64/lin/aarch64-linux/bin:/tools/Xilinx/Vitis/2020.1/gnu/aarch64/lin/aarch64-none/bin:/tools/Xilinx/Vitis/2020.1/gnu/armr5/lin/gcc-arm-none-eabi/bin:/tools/Xilinx/Vitis/2020.1/tps/lnx64/cmake-3.3.2/bin:/tools/Xilinx/Vitis/2020.1/cardano/bin:/tools/Xilinx/Vivado/2020.1/bin:/tools/Xilinx/DocNav:/home/eli/.bin_:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> LD_LIBRARY_PATH : /opt/xilinx/xrt/lib:
> PYTHONPATH     : /opt/xilinx/xrt/python:
> Configured: settings.tcl
> ----
> set XPART xcu200-fsgd2104-2-e
> set CSIM 1
> set CSYNTH 0
> set COSIM 0
> set VIVADO_SYN 0
> set VIVADO_IMPL 0
> set XF_PROJ_ROOT "/home/eli/gitee/Vitis_Libraries/vision/"
> set OPENCV_INCLUDE "/usr/include/opencv2"
> set OPENCV_LIB "/usr/lib/x86_64-linux-gnu"
> set CUR_DIR "/home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm"
> ----
> vitis_hls -f run_hls.tcl;
> 
> ****** Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.1.1 (64-bit)
>   **** SW Build 2960000 on Wed Aug  5 22:57:21 MDT 2020
>   **** IP Build 2956692 on Thu Aug  6 01:41:30 MDT 2020
>     ** Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
> 
> source /tools/Xilinx/Vitis/2020.1/scripts/vitis_hls/hls.tcl -notrace
> INFO: [HLS 200-10] Running '/tools/Xilinx/Vitis/2020.1/bin/unwrapped/lnx64.o/vitis_hls'
> INFO: [HLS 200-10] For user 'eli' on host 'elli-A17-R4' (Linux_x86_64 version 5.4.0-52-generic) on Thu Oct 22 14:02:26 CST 2020
> INFO: [HLS 200-10] On os Ubuntu 18.04.5 LTS
> INFO: [HLS 200-10] In directory '/home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm'
> Sourcing Tcl script 'run_hls.tcl'
> INFO: [HLS 200-10] Opening and resetting project '/home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm/sgbm.prj'.
> WARNING: [HLS 200-40] No /home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm/sgbm.prj/sol1/sol1.aps file found.
> INFO: [HLS 200-10] Adding design file '/home/eli/gitee/Vitis_Libraries/vision//L1/examples/sgbm/xf_sgbm_accel.cpp' to the project
> INFO: [HLS 200-10] Adding test bench file '/home/eli/gitee/Vitis_Libraries/vision//L1/examples/sgbm/xf_sgbm_tb.cpp' to the project
> INFO: [HLS 200-10] Creating and opening solution '/home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm/sgbm.prj/sol1'.
> INFO: [HLS 200-10] Cleaning up the solution database.
> WARNING: [HLS 200-40] No /home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm/sgbm.prj/sol1/sol1.aps file found.
> INFO: [HLS 200-1505] Using default flow_target 'vivado'
> Resolution: For help on HLS 200-1505 see www.xilinx.com/html_docs/xilinx2020_1/hls-guidance/200-1505.html
> INFO: [HLS 200-10] Setting target device to 'xcu200-fsgd2104-2-e'
> INFO: [SYN 201-201] Setting up clock 'default' with a period of 3.3ns.
> INFO: [SIM 211-2] *************** CSIM start ***************
> INFO: [SIM 211-4] CSIM will launch GCC as the compiler.
> make[1]: Entering directory '/home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm/sgbm.prj/sol1/csim/build'
>    Compiling ../../../../xf_sgbm_tb.cpp in debug mode
>    Compiling ../../../../xf_sgbm_accel.cpp in debug mode
>    Generating csim.exe
> Makefile.rules:379: recipe for target 'csim.exe' failed
> make[1]: Leaving directory '/home/eli/gitee/Vitis_Libraries/vision/L1/examples/sgbm/sgbm.prj/sol1/csim/build'
> /usr/lib/libgdal.so.20: undefined reference to `xmlBufferFree@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlBufferCreate@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathRegisterNs@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlNanoHTTPCleanup@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterEndElement@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlSearchNs@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlCreateFileParserCtxt@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlBufferCreateSize@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaSetValidErrors@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libtbb.so.2: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlAddNextSibling@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathNewContext@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlSetGenericErrorFunc@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathNewString@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlBufferContent@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterStartElementNS@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlAddPrevSibling@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterSetIndentString@LIBXML2_2.6.5'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlAddChild@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlCatalogResolveURI@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaNewMemParserCtxt@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlCheckVersion@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlSetNs@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterEndDocument@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlNewText@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaSetParserErrors@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterWriteString@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaValidateFile@LIBXML2_2.6.20'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlBufferSetAllocationScheme@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaParse@LIBXML2_2.5.8'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathEvalExpression@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlReadFile@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlParseDocument@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlGetExternalEntityLoader@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlFreeNode@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathErr@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathFreeContext@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterEndPI@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathFreeObject@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlNodeDump@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaNewValidCtxt@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlXPathFreeCompExpr@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlXPathCompile@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathRegisterFunc@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlReplaceNode@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `valuePush@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterWriteRaw@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterWriteElement@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaValidateDoc@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlCreatePushParserCtxt@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlXPathBooleanFunction@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlSearchNsByHref@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlGetLastError@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlParseChunk@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterWriteAttribute@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlParseDoc@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlSchemaNewDocParserCtxt@LIBXML2_2.6.2'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlCleanupParser@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlNewTextWriterMemory@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlDocDumpFormatMemory@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `valuePop@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSetExternalEntityLoader@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterStartPI@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlSAX2GetLineNumber@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlNewStringInputStream@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterStartElement@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlFree@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaFree@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterSetIndent@LIBXML2_2.6.5'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaFreeParserCtxt@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlTextWriterStartDocument@LIBXML2_2.6.0'
> /usr/lib/libgdal.so.20: undefined reference to `xmlDocGetRootElement@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlFreeDoc@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlCatalogResolveSystem@LIBXML2_2.4.30'
> /usr/lib/libgdal.so.20: undefined reference to `xmlSchemaFreeValidCtxt@LIBXML2_2.5.8'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlInitParser@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlFreeParserCtxt@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlNewNs@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlNewNode@LIBXML2_2.4.30'
> /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined reference to `xmlReadMemory@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlFreeTextWriter@LIBXML2_2.6.0'
> /usr/lib/x86_64-linux-gnu/libdap.so.25: undefined reference to `xmlGetPredefinedEntity@LIBXML2_2.4.30'
> collect2: error: ld returned 1 exit status
> make[1]: *** [csim.exe] Error 1
> ERROR: [SIM 211-100] 'csim_design' failed: compilation error(s).
> INFO: [SIM 211-3] *************** CSIM finish ***************
> 4
>     while executing
> "source run_hls.tcl"
>     ("uplevel" body line 1)
>     invoked from within
> "uplevel \#0 [list source $arg] "
> 
> INFO: [Common 17-206] Exiting vitis_hls at Thu Oct 22 14:02:34 2020...
> Makefile:251: recipe for target 'runhls' failed
> make: *** [runhls] Error 1

**Comment by vt-lib-support** [comment]
@3togo 
This seems to be an issue with the Vitis tool and the OS compatibility. Please post in [Xilinx Forums](https://forums.xilinx.com/t5/Vitis-Acceleration-SDAccel-SDSoC/bd-p/tools_v) for further help.
