### ISSUE TITLE
Gzip decompression error with Alveo U50

### ISSUE THREAD

**Issue by dajovu2020** [Xilinx/Vitis_Libraries#36]
Hi,

We have tried to use Gzip decompression/compression with Alveo U50.
Here are the errors when use the default test and our customized test data.

- Hardware platform: Alveo U50
- OS: Ubuntu 18.04
- XRT: xrt_202010.2.7.766_18.04-amd64-xrt.deb

1) make run TARGET=hw DEVICE=u50
    Error message as below.
<img width="697" alt="截圖 2020-11-17 下午3 33 25" src="https://user-images.githubusercontent.com/74596221/99377777-95cedb80-2901-11eb-88da-850106cc050f.png">

2) We use the test data as the below website.
     http://sun.aei.polsl.pl/~sdeor/index.php?page=silesi
    The compression of all data are good but there are errors when decompression.
    Error message as below.
<img width="697" alt="截圖 2020-11-17 下午3 35 50" src="https://user-images.githubusercontent.com/74596221/99377923-ce6eb500-2901-11eb-8a38-298c749b7161.png">

**Comment by vt-lib-support** [comment]
@dajovu2020  Please try gzip demo located at L3/demos/gzip_hbm this demo supports U50.
Link: https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression/L3/demos/gzip_hbm

**Comment by dajovu2020** [comment]
![截圖 2020-11-20 下午3 39 41](https://user-images.githubusercontent.com/74596221/99773564-9789e080-2b47-11eb-9c08-c490cebe127e.png)
Hi, 
We have tried L3 but there are the other errors message as the attachment.
Are there anything that we can to modify?
Thanks.

**Comment by vt-lib-support** [comment]
Hi @dajovu2020  Please re-run the build and ensure your machine is dedicated for only this.

**Comment by vt-lib-support** [comment]
@dajovu2020  since there is no more update on this item. Closing this issue in case if you face trouble reopen or create a new one with logs.
