### ISSUE TITLE
dsp FFT has no L2 Benchmarks?

### ISSUE THREAD

**Issue by zy486at189cn** [Xilinx/Vitis_Libraries#37]
document https://github.com/Xilinx/Vitis_Libraries/blob/master/dsp/docs/src/benchmarks/L2_fft_benchmark.rst say:
List of Benchmarks
To the run the benchmarks user has to checkin the Xilinx Vitis libraries. Go to dsp/L2/benchmarks/FPGA folder which contains the Vitis FFT benchmarks. This folder contains different benchmarks for 1D and 2D FFTs as shown below:

1dFix : 1D Fix Point FFT Benchmark
1dFloat : 1D Floating Point FFT Benchmark
2dFix : 2D Fix Point FFT Benchmark
2dFloat : 2D Floating Point FFT Benchmark
Building and Running the Benchmarks

but at github ,the vitis_libraries has no FFT L2 benchmarks,where can I download the FFT L2 benchmarks?or When will Xilinx release the   FFT L2 benchmarks?
Thanks!

**Comment by vt-lib-support** [comment]
Hi stockerc,

This doc source file was wrongly included into git. We don't have a schedule for getting DSP L2 APIs or benchmarks ready for release yet.
