### ISSUE TITLE
Alveo U200 & U250 - Data center FPGA board platforms

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/Vitis_Libraries#4]
Hi,

For Xilinx Edge device, board platform source given here - https://github.com/Xilinx/Vitis_Embedded_Platform_Source

From where I can get board platforms for Data center cards - Alveo U200 & U250?

**Comment by mahinlma** [comment]
@luciferlee , Please provide clarification on this.

**Comment by songc-xil** [comment]
Platforms for Alveo U200 and U250 can be found here:
https://www.xilinx.com/products/boards-and-kits/alveo/u200.html#gettingStarted
https://www.xilinx.com/products/boards-and-kits/alveo/u250.html#gettingStarted

**Comment by mahinlma** [comment]
@songc-xil , Thank you.
I required "xilinx_u200_xdma_201830_1.xpfm", Please let me know, how to get this.
There is no directory named "Platform" under /opi/xilinx/

**Comment by mahinlma** [comment]
@songc-xil 
From where I can get Hardware specification (XSA) for Alveo 200 & 250

**Comment by songc-xil** [comment]
Download the "Development Target Platform" from the links I posted, and install them in your system, you should be able to see the XSA for Alveo U200/U250 under /opt/xilinx/..

**Comment by mahinlma** [comment]
@songc-xil , Thank you

**Comment by chenruiqiu** [comment]
hello,i am test the Opencv resize,but i can not find the xpfm of u200，while i have finish these steps in the picture
![xpfm](https://user-images.githubusercontent.com/41660063/169643284-0930ef9a-f51c-43e1-aa38-3231253f0525.png)
