### ISSUE TITLE
Bug in `quantitative_finance/L2/tests/MCEuropeanEngine` for `timeSteps >= 2` (affects sw_emu, hw_emu and real deployment on AWS f1)

### ISSUE THREAD

**Issue by diamantopoulos** [Xilinx/Vitis_Libraries#59]
Dear Vitis_Libraries maintainers,

it seems that there is a bug in `https://github.com/Xilinx/Vitis_Libraries/blob/master/quantitative_finance/L2/tests/MCEuropeanEngine/` when the user selects a value for `timeSteps >= 2`.

The bug should be in the internal MCE kernel and not part of the host code.
Specifically I suspend the bug is in `https://github.com/Xilinx/Vitis_Libraries/blob/master/quantitative_finance/L2/include/xf_fintech/mc_engine.hpp`  and following the hierarchy to L1 can be in `https://github.com/Xilinx/Vitis_Libraries/blob/master/quantitative_finance/L1/include/xf_fintech/mc_simulation.hpp` or other kernel used from L1.

These are the steps to replicate the bug:
```
source <install path>/Vitis/2020.2/settings64.sh
source /opt/xilinx/xrt/setup.sh
export PLATFORM_REPO_PATHS=/opt/xilinx/platforms
cd Vitis_Libraries/quantitative_finance/L2/tests/MCEuropeanEngine
# vim host/test.cpp :  edit the line "unsigned int timeSteps = 2;" : Add any value higher than 1

#  software emulation
make run TARGET=sw_emu DEVICE=u250_xdma_201830_1
```
Upon this simulation you get this output: 

```
XCL_EMULATION_MODE=sw_emu build_dir.sw_emu.u250_xdma_201830_2/test.exe -xclbin build_dir.sw_emu.u250_xdma_201830_2/mc_euro_k.xclbin
[INFO]Running in sw_emu mode
Found Platform
Platform Name: Xilinx
Found Device=xilinx_u250_xdma_201830_2
INFO: Importing build_dir.sw_emu.u250_xdma_201830_2/mc_euro_k.xclbin
Loading: 'build_dir.sw_emu.u250_xdma_201830_2/mc_euro_k.xclbin'
kernel has been created
kernel start------
WARNING: Hls::stream 'hls::stream<float, 0>.6' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<float, 0>.10' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<float, 0>.18' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<float, 0>.22' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'hls::stream<float, 0>.30' contains leftover data, which may result in RTL simulation hanging.
...
```
This is a well-known HLS warning when a FIFO is not read for the same number of times with the number of times that it was written ( #push() != #pop() ), resulting in leftover data in the FIFO.
Eventually, in the case above, the `csim` (i.e. sw_emu) can be successfully finish (with lengthy warning like the above), but the `cosim` (i.e. hw_emu) hangs. 

In case of building a bitstream and uploading to AWS (using https://github.com/aws/aws-fpga/ tooflow) the execution hangs, while for `timeSteps = 1` it is executed as expected. 

Please note that this is a very important parameter of the Monte-Carlo simulation as it is the number of simulation steps for every path. As a result, having the MCE kernel operating only for `timeSteps == 1` decreases the simulation timing discretization to just one step (e.g. one second, day, month, year, i.e. whatever is your parameter modeling.... but only one!). Depending on the HLS implementation, this step could highly affect the simulation time and can result in unfair CPU-FPGA speedup comparisons for real-word Monte-carlo simulations, which may have several 100s or 1000s of time steps.
 
The bug exists in all tagged version until now. Specifically:
* `Vitis 2020.1` and `Vitis Libraries v2020.1_rel (208ada169)`
* `Vitis 2020.2` and `Vitis Libraries v2020.2_rel (836c05963)`

It is also irrelevant of the selected platform. Tried:
* `u250_xdma_201830_2` (for `sw_emu` and `hw_emu`)
* `xilinx_aws-vu9p-f1_shell-v04261818_201920_2 ` (for `sw_emu` and `hw_emu`, and  on aws with Vitis 2020.1)

Thanks and regards,
Dionysios

**Comment by vt-lib-support** [comment]
This issue has been identified and resolved.

Fix will be propagated to the branch asap.
