### ISSUE TITLE
SVD benchmark reads xclbin filename from env, not -xclbin

### ISSUE THREAD

**Issue by cathalmccabe** [Xilinx/Vitis_Libraries#7]
host.exe checks for xclbin name from environment variable
https://github.com/Xilinx/Vitis_Libraries/blob/40b98f7a20d4f9d181642104f74d797a94315024/quantitative_finance/L1/benchmarks/SVD/src/main.cpp#L21

However, instructions indicate xclbin should be passed as parameter:
https://github.com/Xilinx/Vitis_Libraries/tree/master/quantitative_finance/L1/benchmarks/SVD

**Comment by vt-lib-support** [comment]
issue fixed
