### ISSUE TITLE
`Array2xfMat()` and co. require a `PTR_WIDTH` which must be a power of 2

### ISSUE THREAD

**Issue by goekce** [Xilinx/Vitis_Libraries#70]
The document [Getting started with Vitis vision](https://github.com/Xilinx/Vitis_Libraries/blob/master/vision/docs/getting-started-with-vitis-vision.rst) states that `Array2xfMat()` and co. require a `PTR_WIDTH` which must be a power of 2. Is this just a convention for Vitis kernel flow or a requirement? I read in [wrappers around HLS kernels section](https://github.com/Xilinx/Vitis_Libraries/blob/master/vision/docs/getting-started-with-vitis-vision.rst#wrappers-around-hls-kernels):

```
Vitis flow (OpenCL) requires kernel interfaces to be memory pointers with width in power(s) of 2.
```

I recently tried to synthesize a kernel with a 24bit streaming interface using `axiStrm2xfMat<24, ...>` which worked in simulation but not on the board. I am just curious that the reason could be this `PTR_WIDTH` enforcement.

**Comment by vt-lib-support** [comment]
It should work in c-simulation and software emulation, but will fail in co-simulation, hardware emulation and on the hardware. 
The requirement comes from AXI protocol where the data bus width should be powers of 2 and PTR_WIDTH is used as AXI data bus width.
