### ISSUE TITLE
Vision docs include an outdated user guide

### ISSUE THREAD

**Issue by goekce** [Xilinx/Vitis_Libraries#71]
https://github.com/Xilinx/Vitis_Libraries/blob/master/vision/docs/getting-started-with-vitis-vision.rst#kernel-to-kernel-streaming

states `refer to the "Streaming Data Transfers Between the Kernels" section of UG1277 document.`, but UG1277 does not seem to exist in 2020.2 release.

Can someone verify this?

**Comment by ThomasXilinx** [comment]
It should be UG1399, not UG1277. Here is a link to the HTML version:
https://www.xilinx.com/html_docs/xilinx2020_2/vitis_doc/streamingconnections.html#qwz1555342848145

**Comment by vt-lib-support** [comment]
Corrected the document number and the link in the latest release.
