### ISSUE TITLE
Vitis_Libraries/data_compression/L2/tests/gzipc/description.json

### ISSUE THREAD

**Issue by wanyuzhan** [Xilinx/Vitis_Libraries#76]
Hi, in order to run gzipc in Vitis GUI, I tried to find all kernel codes in the gzipc project. Shall I know which files belong to the kernel?
Also, some files not found in kernel when I did the software emulation.  Shall I know how to solve it?
![Screen Shot 2021-07-31 at 9 38 00 PM](https://user-images.githubusercontent.com/43864322/127759436-10f2bc7e-2efb-477b-98dd-620d9b893851.png)

**Comment by meghana-t** [comment]
Hi @wanyuzhan 
1. You can trace kernel files from description.json "accelerator" section: 
![image](https://user-images.githubusercontent.com/89925825/131692920-3b62e1bc-9b74-4e6a-9128-5a14dc1dd6b8.png)

For L2/tests/gzipc project, kernel files are found at https://github.com/Xilinx/Vitis_Libraries/blob/master/data_compression/L2/src/gzip_compress_multicore_stream.cpp as mentioned in description.json. 

2. All the kernel include files are added in description.json as part of vitis " v++ compiler / includepaths". 
![image](https://user-images.githubusercontent.com/89925825/131695033-0a9fc1ba-dde9-44cd-a9f8-86684b7ca4d1.png)
https://github.com/Xilinx/Vitis_Libraries/blob/master/data_compression/L2/tests/gzipc/description.json#L66

3. Could you please create application project in Vitis GUI as and try software emulation again ? I don't find any kernel files missing in this case. 
![image](https://user-images.githubusercontent.com/89925825/131693980-55f7eba5-08a9-4934-9587-5f2d0d0d4753.png)

Let me know if you still face any other issues.

**Comment by wanyuzhan** [comment]
Thanks for your reply. I downloaded Vitis_Libraries in Vitis GUI and ran Vitis_Libraries/data_compression/L2/tests/gzipc. In this case, I successfully did the software emulation. However, when I launched the software,  I encountered the following error. I sincerely hope to get your help。
<img width="698" alt="Screen Shot 2021-08-19 at 6 57 26 PM" src="https://user-images.githubusercontent.com/43864322/131727189-77c2d579-39b9-4cb7-b25a-2a6183240a48.png">

**Comment by meghana-t** [comment]
Hi @wanyuzhan 
I hope you are trying correct steps while building for software emulation first. You can check below steps and follow the same. 

1. create application project 
![image](https://user-images.githubusercontent.com/89925825/131776042-00a6e914-98cc-489d-894d-77c26fa731f4.png)

2. Build for complete **system project** 
![image](https://user-images.githubusercontent.com/89925825/131776251-e16cdb38-35ec-4e1a-81af-05cabed6e8db.png)

3. Once build is successful, xclbin is generated. 
![image](https://user-images.githubusercontent.com/89925825/131776482-03d691c7-58ba-434c-ae48-3062d97ad6d3.png)

4. Launch / run software emulation using ![image](https://user-images.githubusercontent.com/89925825/131776589-244203e0-520a-481a-9b15-db329b752378.png)

5. Check for console output on successful run.

**Comment by wanyuzhan** [comment]
Thanks for your tips. I need to say I run the program using the steps you mentioned. But when I Launch software emulation, I met this error. 
<img width="698" alt="Screen Shot 2021-08-19 at 6 57 26 PM" src="https://user-images.githubusercontent.com/43864322/131780060-aebe076d-428c-4ea0-8fcb-da6e439d9dbc.png">

**Comment by meghana-t** [comment]
Hi @wanyuzhan 
Can you please point me to the gzip_system_hw_link directory in the explorer view ? Need to make sure if xclbin is actually generated or its unreadable. 
Also, make sure you setting up the vitis environment correctly https://www.xilinx.com/html_docs/xilinx2021_1/vitis_doc/settingupvitisenvironment.html#zks1565446519267 before launching the vitis IDE. For complete GUI flow, please refer below: 
https://www.xilinx.com/html_docs/xilinx2021_1/vitis_doc/creatingvitisideproject.html#cpe1508968036414

**Comment by meghana-t** [comment]
Hi @wanyuzhan 
Could you please share the complete steps you tried alongwith the environment settings ?

**Comment by wanyuzhan** [comment]
Thanks for your reply. Now I launch this program successfully and get this following result. However,I can't find a file from which I can get this result. Also, Which is the file that reads the sample.txt?
<img width="444" alt="Screen Shot 2021-09-06 at 6 48 40 PM" src="https://user-images.githubusercontent.com/43864322/132272028-1bc93b9c-fd3f-4129-916a-c2642807dd42.png">

**Comment by meghana-t** [comment]
Hi @wanyuzhan 
You can check the input <sample.txt> and generated output <sample.txt.gz> in data folder as below: 
![image](https://user-images.githubusercontent.com/89925825/132290282-dba96b94-77e2-4a7a-951a-cfdbd961bf7a.png)

Same location you can trace using terminal (CLI) from your workspace area as : /<path/to/workspace>/gzip/data/

**Comment by wanyuzhan** [comment]
Thanks for your reply! I'm sorry to have failed to make myself clear. My question is which part of the code in this project is used to read input file(sample.txt)? I want to read a different file instead of sample.txt but I didn't find where to change.

**Comment by meghana-t** [comment]
Hi @wanyuzhan 
You can update arguments in run configuration to parse new file, please follow below steps: 
1. Click on run configuration 
![image](https://user-images.githubusercontent.com/89925825/132301420-880c7887-ecbe-4a3c-a6a6-607c67f3cc55.png)

2. Click Edit .. next to program arguments
![image](https://user-images.githubusercontent.com/89925825/132301604-4be4d38c-4069-4c34-9be5-6e099e2ba1b7.png)

3. Click to edit and update the new filename. Make sure new file is present at correct location. 
![image](https://user-images.githubusercontent.com/89925825/132301961-d31d880e-9eb4-4fe7-a9b9-a823a06e6cbb.png)

4. Proceed to click OK .. and click Run. 
![image](https://user-images.githubusercontent.com/89925825/132302261-1b6f72ae-659b-495a-9aef-724f1708f7cd.png)

5. Check the console output for successful run. 

File read / handling is done here: https://github.com/Xilinx/Vitis_Libraries/blob/master/data_compression/common/libs/compress/compressApp.cpp#L230

**Comment by wanyuzhan** [comment]
Thanks for your help! I already know IDE usage and I believe this is a good start. I was grateful for your wise counsel.

**Comment by heeran-xilinx** [comment]
Thanks @wanyuzhan . We  are closing this issue assuming that it is resolved.
