### ISSUE TITLE
CSim failure while buidling L1 examples

### ISSUE THREAD

**Issue by kinaikan** [Xilinx/Vitis_Libraries#77]
Hi,
I'm trying to build one of the L1 examples ( `resize` ), targeting `xc7z020-clg400-1`, however no matter what settings I try, C Simulation always fails with following error:

![00001](https://user-images.githubusercontent.com/85876694/128340564-ae9f76c7-8b77-4151-be7b-3c1b6007ca86.png)

I'm trying to build the project on my x64 Windows 10 `build 19042.1110` machine. I'm using Vitis HLS 2020.2 `build 3064766`.
I compiled and build opencv-3.4.11 CMake and MinGW using MinGW configurations in CMake.

my environmental variables are set as noted in Vitis documents:

![00002](https://user-images.githubusercontent.com/85876694/128341763-60f58553-6d84-4dcf-9c94-c2714ffa754f.png)

I tried to build the project using .tcl provided [here](https://www.xilinx.com/support/answers/75727.html) and also using GUI.

in both cases I also setup the Linker Flags and CFlags.
 
but I always end up here:

![00003](https://user-images.githubusercontent.com/85876694/128342224-7b4251f6-13b7-42dd-987c-6d9888a770b7.png)
with this particular example, I just did a slightly modification to CFlag values and changed the `-std=c++0x` to `-std=c++14`.
 cause while I try to build with `-std=c++0x` I get some warnings about template files which are just supported  with c++14.

Following the trace logs, doesn't tell anything particular to me (sorry if they have to; it's my bad).

any help or suggestion would be appreciated, cause I don't have any clue what I'm doing wrong.

Thanks

**Comment by vt-lib-support** [comment]
Hi @kinaikan,

Vitis Vision Libraries are not officially supported on Windows OS. 

We suggest you to use any of the supported operating systems listed [here](https://www.xilinx.com/html_docs/xilinx2021_1/vitis_doc/acceleration_installation.html#ariaid-title2).

**Comment by m-tosch** [comment]
Is there a plan to support Windows OS for the Vitis Vision Libraries?
