### ISSUE TITLE
Quantitative Finance SVD -support for newer shells

### ISSUE THREAD

**Issue by cathalmccabe** [Xilinx/Vitis_Libraries#8]
Only older shell version currently supported (201830_1?)

https://github.com/Xilinx/Vitis_Libraries/blob/40b98f7a20d4f9d181642104f74d797a94315024/quantitative_finance/L1/benchmarks/SVD/Makefile#L230

Adding switch in makefile for 2019 shell with -sp DDR[0] (instead of "bank0") would allow design to be run with more recent shell(s)

E.g. This works for U250 xilinx_u250_qdma_201920_1 (but not tested with other 2019 shells; different awk pattern match may be needed):

else ifneq (,$(shell echo $(XPLATFORM) | awk '/u2[50]0/*/2019/'))
    VPP_CFLAGS += --sp $(KERNEL)_0.m_axi_gmem0:DDR[0]
    VPP_CFLAGS += --sp $(KERNEL)_0.m_axi_gmem1:DDR[0]
    VPP_CFLAGS += --sp $(KERNEL)_0.m_axi_gmem2:DDR[0]
    VPP_CFLAGS += --sp $(KERNEL)_0.m_axi_gmem3:DDR[0]

**Comment by vt-lib-support** [comment]
Alveo U200, U250 and U50 are supported
