### ISSUE TITLE
Fail to build spmv

### ISSUE THREAD

**Issue by xiupingcui** [Xilinx/Vitis_Libraries#82]
When running the command
```make run PLATFORM_REPO_PATHS=$XILINX_VITIS/platforms  DEVICE=xilinx_u280_xdma_201920_3  TARGET=hw```
in sparse/L2/tests/fp64/spmv directory, an error occurred:
```ERROR: [VPL 17-153] Param 'hd.enableClockTrackSelectionEnancement' does not exist```
My VITIS version is 2020.1. 
How can I solve this problem?
Thank you!

**Comment by lisaliu1** [comment]
please try with vitis 2021.1

**Comment by xiupingcui** [comment]
Thank you
