### ISSUE TITLE
How to view and modify the API In Vitis_Libraries/data_compression/L2 / tests/ gzipc_block_mm 

### ISSUE THREAD

**Issue by wanyuzhan** [Xilinx/Vitis_Libraries#83]
The screenshot below shows the kernel code "gzip_compress_multicore_mm.cpp" in the Vitis_ library calls three APIs to do the compression. But I cannot find where the API internal code is. I would like to know which code implements compression in this project. The introduction of the Vitis accelerator mentions that customers can use Vitis library functions as optimized algorithmic building blocks and modify them. I guess if I want to modify the code, I need to find all the source code first. Or shall I get some suggestions, like what parts can customers modify? 
![Screen Shot 2021-09-20 at 6 42 10 PM](https://user-images.githubusercontent.com/43864322/134099414-29fc0291-948f-4304-8604-efc8b4835ecd.png)

Moreover, This screenshot below shows this project's timeline trace. I found I find that some running modules have blank time between them. Is this latency? Or is there any other explanation for this？
<img width="1360" alt="Screen Shot 2021-09-18 at 6 12 06 PM" src="https://user-images.githubusercontent.com/43864322/134099364-8cf7435c-a379-4214-a799-57b0744f0da5.png">

**Comment by rbhartari-xilinx** [comment]
Hi @wanyuzhan,

You can find the source code files for all the internal modules of any kernel at below path in repo:
[Vitis_Libraries/data_compression/L1/include/hw/](https://github.com/Xilinx/Vitis_Libraries/tree/master/data_compression/L1/include/hw)

Please refer below image for explanation of timeline trace screenshot.
![git_query_1](https://user-images.githubusercontent.com/91119097/134138100-465c1082-c2e3-4131-817f-5c3c57f672e5.png)

The gaps visible are between the subsequent OpenCL API calls in the host code, while host code executes.

**Comment by heeran-xilinx** [comment]
closing this issue as no respond to last comment. Please re-open if issue still exist and provide more info to reproduce it.
