### ISSUE TITLE
Corner update function error

### ISSUE THREAD

**Issue by wenyee9797** [Xilinx/Vitis_Libraries#90]
When I call the xf_corner_update.hpp inside the L1 include, the error pop up, it seems like library bug, does anyone meet the same issue?

<-- Error information below -->
caught Tcl error: ERROR: [HLS 207-2276] cannot cast from type 'xf::cv::Mat<3, 360, 640, 1, 2>::_DATATTYPE' (aka 'hls::stream<ap_uint<32>, 2>') to pointer type 'unsigned int *: Vitis_libraries/vision/L1/include/imgproc/xf_corner_update.hpp:31:40

**Comment by norabarlow** [comment]
I also encounter the same error.

**Comment by wenyee9797** [comment]
I change it to this, the problem solve and works in Vitis flow

for(int i=0;i<height;i++) {
        for(int j=0;j<width;j++) {
            flowvectorsDataPtr[i*width+j] = (unsigned int)flow_vectors.read(i*width+j);
        }
    }

**Comment by vt-lib-support** [comment]
Hi @wenyee9797, @norabarlow ,

cornerUpdate is a memory mapped function. Hence, -D__SDA_MEM_MAP__ flag needs to be passed to the compiler. Example [here](https://github.com/Xilinx/Vitis_Libraries/blob/master/vision/L3/examples/cornertracker/Makefile#L212)

**Comment by norabarlow** [comment]
That works, thanks!
