### ISSUE TITLE
Duplicate include guard names in xf_erosion.hpp and xf_median_blur.hpp

### ISSUE THREAD

**Issue by dsp-avt** [Xilinx/Vitis_Libraries#96]
In the Vitis Vision Library ``xf_erosion.hpp`` defines ``_XF_MEDIAN_BLUR_`` as an include guard, however, ``xf_median_blur.hpp`` also uses this same name.  The include guard name in ``xf_erosion.hpp`` should be changed to ``_XF_EROSION_`` to allow both ``xf::cv::erode()`` and ``xf::cv::medianBlur()`` to be used in the same accelerator.

**Comment by vt-lib-support** [comment]
Hi @dsp-avt ,

Thanks for reporting this. We will correct it soon.

**Comment by vt-lib-support** [comment]
Hi @dsp-avt ,

This has been corrected in the latest release.
