### ISSUE TITLE
xf_erosion.hpp has an improper header definition

### ISSUE THREAD

**Issue by ethansieg** [Xilinx/Vitis_Libraries#99]
file /vision/L1/include/imgproc/xf_erosion.hpp has the following header DEFINE statement:

#ifndef _XF_MEDIAN_BLUR_
#define _XF_MEDIAN_BLUR_

Therefore, if xf_erosion.hpp is combined with xf_median_blur.hpp there will be a compile error.

**Comment by vt-lib-support** [comment]
Duplicate to #96

**Comment by vt-lib-support** [comment]
Fixed with 2022.1 release
